[package]
name = "happy_feet"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.3.0"
bevy = "0.16.0"
itertools = "0.14.0"
rand = "0.9.1"
smallvec = "1.14.0"

[dev-dependencies]
bevy_enhanced_input = "0.12.0"
bevy_skein = "0.2.1"
