[package]
name = "happy_feet"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.2.1"
bevy = "0.15.2"
rand = "0.9.0"
smallvec = "1.14.0"
bevy_transform_interpolation = "0.1.0"

[dev-dependencies]
bevy_transform_interpolation = "0.1.0"
